name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 171961474458.dkr.ecr.us-east-1.amazonaws.com
      FRONTEND_TAG: frontend-v1
      USERS_TAG: users-v1
      STATUS_TAG: status-v1
      NGINX_TAG: nginx-v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker Images
        run: |
          docker build -t frontend ./frontend
          docker build -t users-service ./services/users-service
          docker build -t status-service ./services/status-service
          docker build -t nginx-service ./nginx

          docker tag frontend:latest $ECR_REGISTRY/frontend:$FRONTEND_TAG
          docker tag users-service:latest $ECR_REGISTRY/services:$USERS_TAG
          docker tag status-service:latest $ECR_REGISTRY/services:$STATUS_TAG
          docker tag nginx-service:latest $ECR_REGISTRY/nginx-service:$NGINX_TAG

          docker push $ECR_REGISTRY/frontend:$FRONTEND_TAG
          docker push $ECR_REGISTRY/services:$USERS_TAG
          docker push $ECR_REGISTRY/services:$STATUS_TAG
          docker push $ECR_REGISTRY/nginx-service:$NGINX_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 Public DNS/IP, NO http/https
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}         # private key content
          script: |
            cd /home/ubuntu/Docker

            # Login to ECR
            aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin 171961474458.dkr.ecr.us-east-1.amazonaws.com

            # Pull latest images
            sudo docker-compose pull

            # Recreate containers
            sudo docker-compose up -d --force-recreate
