name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 171961474458.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, Tag and Push Docker Images
        run: |
          # Frontend
          docker build -t frontend ./frontend
          docker tag frontend:latest 171961474458.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
          docker push 171961474458.dkr.ecr.us-east-1.amazonaws.com/frontend:v1

          # Nginx
          docker build -t nginx-service ./nginx
          docker tag nginx-service:latest 171961474458.dkr.ecr.us-east-1.amazonaws.com/nginx-service:nginx-v1
          docker push 171961474458.dkr.ecr.us-east-1.amazonaws.com/nginx-service:nginx-v1

          # Users Service
          docker build -t users-service ./services/users-service
          docker tag users-service:latest 171961474458.dkr.ecr.us-east-1.amazonaws.com/services:users-v1
          docker push 171961474458.dkr.ecr.us-east-1.amazonaws.com/services:users-v1

          # Status Service
          docker build -t status-service ./services/status-service
          docker tag status-service:latest 171961474458.dkr.ecr.us-east-1.amazonaws.com/services:status-v1
          docker push 171961474458.dkr.ecr.us-east-1.amazonaws.com/services:status-v1

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Docker
            git pull origin main
            sudo docker-compose pull
            sudo docker-compose up -d
