name: CI/CD Pipeline

on:
  push:
    branches: [ main ]   # runs when you push to main branch
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build and push Docker images
      - name: Build, Tag, and Push images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Frontend
          docker build -t $ECR_REGISTRY/frontend:frontend-v1 ./frontend
          docker push $ECR_REGISTRY/frontend:frontend-v1

          # Users Service
          docker build -t $ECR_REGISTRY/services:users-v1 ./services/users-service
          docker push $ECR_REGISTRY/services:users-v1

          # Status Service
          docker build -t $ECR_REGISTRY/services:status-v1 ./services/status-service
          docker push $ECR_REGISTRY/services:status-v1

          # Nginx
          docker build -t $ECR_REGISTRY/nginx-service:nginx-v1 ./nginx
          docker push $ECR_REGISTRY/nginx-service:nginx-v1

      # 5. Deploy on EC2 via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Docker
            sudo docker-compose pull
            sudo docker-compose up -d
